### ISSUE TITLE
Stopwatch - IllegalStateException

### ISSUE THREAD

**Issue by galibigid** [StepanMelnik/LargeFileParser#1]
https://github.com/StepanMelnik/LargeFileParser/blob/b0e3de1c44e437083dce2b757405cd105de5c72e/src/main/java/com/sme/bigdata/file/reader/AFileReader.java#L55

stopWatch.stop();
should move to the finally clause in order to prevent possible IllegalStateException exceptions in following calls to
the read function

**Comment by StepanMelnik** [comment]
By design StopWatch instance should not return any state in the reader implementation if an exception occurs while reading a given file.
So, maybe we should not fix anything in the code according to YAGNI principal.

But I like clear code and fixed the problem (see https://github.com/StepanMelnik/LargeFileParser/commit/60977d35b11b45bb918298f5a1be29072ef52188):
* the case covered by StopWatchFileReaderTest.java unit test;
* stopWatch.stop(); moved in final block.

Please review the code and let me know if the issue can be closed.

**Comment by galibigid** [comment]
Yeah the issue can be closed in my opinion.

I don't think there's a need for exposing the stop watch instance.
You can test it via a retry mechanism:

1. "Make" the file unavailable
2. Attempt to read the file which results in runtime exception
3. "Make" the file available
4. Retry reading the file and verify there is no exception that's caused by the stop watch instance
